from tkinter import*
root=Tk()
root.geometry("500x400")
root.configure(bg="pink")
root.resizable(False,False)
l1=Label(root,text="Enter Name:")
l1.grid(row=0,column=0)
t1=Entry(root)
t1.grid(row=0,column=1)
l2=Label(root,text="Enter password:")
l2.grid(row=1,column=0)
t2=Entry(root)
t2.grid(row=1,column=1)
b1=Button(root,text="submit")
b1.grid(row=2,column=1)
root.mainloop()