from tkinter import*
root=Tk()
root.geometry("500x400")
m=IntVar()
r1=Radiobutton(root,text="male",variable=m,value=1)
r1.pack()
r2=Radiobutton(root,text="female",variable=m,value=2)
r2.pack()
singing=IntVar()
dancing=IntVar()
reading=IntVar()
c1=Checkbutton(root,text="singing",variable=singing,onvalue=1,offvalue=0)
c1.pack()
c2=Checkbutton(root,text="dancing",variable=dancing,onvalue=1,offvalue=0)
c2.pack()
c3=Checkbutton(root,text="reading",variable=reading,onvalue=1,offvalue=0)
c3.pack()
menu=StringVar()
menu.set("select country")
d=OptionMenu(root,menu,"UK","INDIA","USA","GERMANY")
d.pack()
l=Listbox(root)
l.insert(1,"red")
l.insert(2,"blue")
l.insert(3,"yellow")
l.pack()
s=Scrollbar(root)
s.pack(side=RIGHT,fill=Y)
l1=Listbox(root,yscrollcommand=s.set)
for i in range(30):
    l1.insert(i,i)
l1.pack(side=LEFT)
s.config(command=l1.yview)
sc=Scale(root,from_=10,to=100,orient=HORIZONTAL)
sc.pack()
root.mainloop()